---
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: demo
  namespace: 3scale-demo
spec:
  name: "demo"
  description: "Demo Backend"
  privateBaseURL: http://demo.apps.lp9nleyq.eastus.aroapp.io
  systemName: "demo-backend"
  mappingRules:
    - httpMethod: GET
      pattern: "/v0"
      increment: 1
      metricMethodRef: hits  
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: demo
  namespace: 3scale-demo
spec:
  name: "demo"
  description: "Demo"
  backendUsages:
    demo-backend:
      path: /
  systemName: "demo-product"
  applicationPlans:
    demo-plan:
      name: "demo"
      published: true
      appsRequireApproval: false
  # deployment:
  #   apicastSelfManaged:
  #     stagingPublicBaseURL: "https://api-3scale-apicast-staging.apps.lp9nleyq.eastus.aroapp.io"
  #     productionPublicBaseURL: "https://api-3scale-apicast-production.apps.lp9nleyq.eastus.aroapp.io"
  #     authentication:
  #       oidc:
  #         issuerEndpoint: "https://keycloak-user2.apps.lp9nleyq.eastus.aroapp.io/auth/realms/microservices-demo/account/"
  #         issuerType: "keycloak"
  #         authenticationFlow:
  #           standardFlowEnabled: false
  #           implicitFlowEnabled: false
  #           serviceAccountsEnabled: true
  #           directAccessGrantsEnabled: false
  #         jwtClaimWithClientID: "azp"
  #         jwtClaimWithClientIDType: "plain" 