---
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: demo
  namespace: 3scale-demo
spec:
  name: "demo"
  description: "Demo Backend"
  privateBaseURL: http://demo.apps.lp9nleyq.eastus.aroapp.io
  systemName: "demo-backend"
  mappingRules:
    - httpMethod: GET
      pattern: "/"
      increment: 1
      metricMethodRef: hits  
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: demo
  namespace: 3scale-demo
spec:
  name: "demo"
  description: "Demo"
  backendUsages:
    demo-backend:
      path: /
  systemName: "demo-product"
  applicationPlans:
    demo-plan:
      name: "demo"
      published: true
      appsRequireApproval: false