---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3scale-demo
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    path: openshift/resources
    directory:
      recurse: true
    repoURL: https://github.com/scottd018-demos/openshift-3scale
  syncPolicy:
    automated:
      selfHeal: true